### ISSUE TITLE
Comparison to fpm

### ISSUE THREAD

**Issue by daurnimator** [paylogic/py2deb#1]
How does py2deb compare to [fpm](https://github.com/jordansissel/fpm)?

**Comment by xolox** [comment]
I'll use this issue as a place to collect notes about how `py2deb` and `fpm` compare. When I'm happy with the comparison I can move it to the readme or documentation. Some initial notes (I hope these don't show my lack of intimate knowledge about `fpm`):

### py2deb converts dependencies recursively (fpm doesn't)

`py2deb` follows Python dependencies during conversion, leaving you with a directory of Debian packages containing everything you need to install a Python package and its dependencies (converted packages that already exist are of course not converted again). I haven't found any way for `fpm` to do this based on the `fpm` command line switches and documentation - it does preserve the metadata about dependencies but it doesn't actually convert the dependencies. It seems this would have to be scripted around `fpm` (unless I've [misread the fpm docs](https://github.com/jordansissel/fpm/wiki/ConvertingPython)).

### py2deb understands system dependencies (fpm doesn't)

`py2deb` understands dependencies on system packages (libraries) and embeds them in the dependencies of the generated packages while `fpm` doesn't. Below is a simple example based on the `lxml` package.

#### lxml converted using fpm

```
peter@work> fpm -s python -t deb lxml
...
peter@work> dpkg -I python-lxml_3.4.2_amd64.deb
 new debian package, version 2.0.
 size 2713492 bytes: control archive= 2940 bytes.
     307 bytes,    11 lines      control              
    8453 bytes,    84 lines      md5sums              
 Package: python-lxml
 Version: 3.4.2
 License: UNKNOWN
 Vendor: none
 Architecture: amd64
 Maintainer: <peter@peter-work>
 Installed-Size: 9552
 Section: default
 Priority: extra
 Homepage: http://lxml.de/
 Description: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
```

Note that the converted package doesn't have any dependencies.

#### lxml converted using py2deb

```
peter@work> py2deb lxml
...
peter@work> dpkg -I /tmp/python-lxml_3.1.0_amd64.deb
 new debian package, version 2.0.
 size 724016 bytes: control archive= 881 bytes.
     320 bytes,     9 lines      control              
     613 bytes,    15 lines   *  postinst             #!/bin/sh
     707 bytes,    18 lines   *  prerm                #!/bin/sh
 Maintainer: lxml dev team <lxml-dev@lxml.de>
 Description: Python package lxml converted by py2deb on February 26, 2015 at 09:40
 Package: python-lxml
 Section: python
 Depends: libc6 (>= 2.14), libxml2 (>= 2.7.4), libxslt1.1 (>= 1.1.26), python2.7
 Priority: optional
 Installed-Size: 2400
 Version: 3.1.0
 Architecture: amd64
```

Note the `Depends:` line. What happened here is that in the background `py2deb` found the `*.so` files in the lxml binary distribution and analyzed them using [dpkg-shlibdeps](http://man.he.net/man1/dpkg-shlibdeps) to find dependencies on system packages. When you install this converted package (on a system different than the system where the package was converted) the necessary system libraries will be pulled in automatically by `apt-get`.

**Comment by daurnimator** [comment]
Thanks for the great comparison already :)

**Comment by xolox** [comment]
Hi @daurnimator and thanks for the feedback! The online documentation now contains [a fairly detailed comparison](https://py2deb.readthedocs.org/en/latest/comparisons.html) between py2deb and dh-virtualenv, stdeb and fpm. I hope this answers your question? :-)

**Comment by xolox** [comment]
I'm closing this issue now because a fairly detailed comparison has been added to the documentation. Thanks for the input @daurnimator!
