### ISSUE TITLE
Small doc change

### ISSUE THREAD

**Issue by brifordwylie** [paylogic/py2deb#6]
There's a snippet of code on http://py2deb.readthedocs.io/en/stable/developers.html?highlight=post#module-py2deb.converter that currently reads:

```
>>> from py2deb import PackageConverter
>>> converter = PackageConverter()
>>> archives, relationships = converter.convert(['py2deb'])
>>> print(archives)
['/tmp/python-py2deb_0.18_all.deb']
>>> print(relationships)
['python-py2deb (=0.18)']
```

I'm pretty sure that first line should be

```
>>> from py2deb.converter import PackageConverter
```

**Comment by xolox** [comment]
Hi Brian and thanks for pointing this out, you are correct. I'll rectify this in the coming days.
